# Build worker image (VM template)
image: Visual Studio 2019

# Start builds on tags only
skip_non_tags: true

# Do not build branches with open Pull Requests
skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

# Build with Release configuration
configuration: Release

# Build Settings
build:
  parallel: true
  project: src/Lavalink4NET.sln
  publish_nuget: true
  public_nuget_symbols: true
  verbosity: detailed